# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/zjc/桌面/pugixml

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/zjc/桌面/pugixml

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/zjc/桌面/pugixml/CMakeFiles /home/zjc/桌面/pugixml/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/zjc/桌面/pugixml/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named xmlconfigtest

# Build rule for target.
xmlconfigtest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 xmlconfigtest
.PHONY : xmlconfigtest

# fast build rule for target.
xmlconfigtest/fast:
	$(MAKE) -f CMakeFiles/xmlconfigtest.dir/build.make CMakeFiles/xmlconfigtest.dir/build
.PHONY : xmlconfigtest/fast

XMLConfig_test.o: XMLConfig_test.cc.o

.PHONY : XMLConfig_test.o

# target to build an object file
XMLConfig_test.cc.o:
	$(MAKE) -f CMakeFiles/xmlconfigtest.dir/build.make CMakeFiles/xmlconfigtest.dir/XMLConfig_test.cc.o
.PHONY : XMLConfig_test.cc.o

XMLConfig_test.i: XMLConfig_test.cc.i

.PHONY : XMLConfig_test.i

# target to preprocess a source file
XMLConfig_test.cc.i:
	$(MAKE) -f CMakeFiles/xmlconfigtest.dir/build.make CMakeFiles/xmlconfigtest.dir/XMLConfig_test.cc.i
.PHONY : XMLConfig_test.cc.i

XMLConfig_test.s: XMLConfig_test.cc.s

.PHONY : XMLConfig_test.s

# target to generate assembly for a file
XMLConfig_test.cc.s:
	$(MAKE) -f CMakeFiles/xmlconfigtest.dir/build.make CMakeFiles/xmlconfigtest.dir/XMLConfig_test.cc.s
.PHONY : XMLConfig_test.cc.s

pugixml.o: pugixml.cpp.o

.PHONY : pugixml.o

# target to build an object file
pugixml.cpp.o:
	$(MAKE) -f CMakeFiles/xmlconfigtest.dir/build.make CMakeFiles/xmlconfigtest.dir/pugixml.cpp.o
.PHONY : pugixml.cpp.o

pugixml.i: pugixml.cpp.i

.PHONY : pugixml.i

# target to preprocess a source file
pugixml.cpp.i:
	$(MAKE) -f CMakeFiles/xmlconfigtest.dir/build.make CMakeFiles/xmlconfigtest.dir/pugixml.cpp.i
.PHONY : pugixml.cpp.i

pugixml.s: pugixml.cpp.s

.PHONY : pugixml.s

# target to generate assembly for a file
pugixml.cpp.s:
	$(MAKE) -f CMakeFiles/xmlconfigtest.dir/build.make CMakeFiles/xmlconfigtest.dir/pugixml.cpp.s
.PHONY : pugixml.cpp.s

xmlconfig.o: xmlconfig.cpp.o

.PHONY : xmlconfig.o

# target to build an object file
xmlconfig.cpp.o:
	$(MAKE) -f CMakeFiles/xmlconfigtest.dir/build.make CMakeFiles/xmlconfigtest.dir/xmlconfig.cpp.o
.PHONY : xmlconfig.cpp.o

xmlconfig.i: xmlconfig.cpp.i

.PHONY : xmlconfig.i

# target to preprocess a source file
xmlconfig.cpp.i:
	$(MAKE) -f CMakeFiles/xmlconfigtest.dir/build.make CMakeFiles/xmlconfigtest.dir/xmlconfig.cpp.i
.PHONY : xmlconfig.cpp.i

xmlconfig.s: xmlconfig.cpp.s

.PHONY : xmlconfig.s

# target to generate assembly for a file
xmlconfig.cpp.s:
	$(MAKE) -f CMakeFiles/xmlconfigtest.dir/build.make CMakeFiles/xmlconfigtest.dir/xmlconfig.cpp.s
.PHONY : xmlconfig.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... xmlconfigtest"
	@echo "... XMLConfig_test.o"
	@echo "... XMLConfig_test.i"
	@echo "... XMLConfig_test.s"
	@echo "... pugixml.o"
	@echo "... pugixml.i"
	@echo "... pugixml.s"
	@echo "... xmlconfig.o"
	@echo "... xmlconfig.i"
	@echo "... xmlconfig.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

